/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.TBBANCO;

import com.toedter.calendar.JDateChooser;
import vista.TBBANCO.fecha;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.Menu;

/**
 *
 * @author usuario
 */

public class CLIENTE extends javax.swing.JFrame {

   Conexion con=new Conexion();
    Connection cnn=con.conexiondb();
    PreparedStatement ps=null;
    ResultSet re=null;
    public CLIENTE() {
        initComponents();
        Cargatabla();
    }
    public void  Cargatabla(){
    DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("Tipo documento");
        tabla.addColumn("Documento");
        tabla.addColumn("Nombre Cliente");
        tabla.addColumn("Apellido Cliente");
        tabla.addColumn("Direccion");
        tabla.addColumn("Telefono");
        tabla.addColumn("Usuario");
        tabla.addColumn("Fecha");
        tablaconsulta.setModel(tabla);
        String datos[]=new String[8];
        try{
            ps=cnn.prepareStatement("SELECT*FROM TBcliente");
            re=ps.executeQuery();
            while(re.next()){
                datos[0]=re.getString(1);
                datos[1]=re.getString(2);
                datos[2]=re.getString(3);
                datos[3]=re.getString(4);
                datos[4]=re.getString(5);
                datos[5]=re.getString(6);
                datos[6]=re.getString(7);
                datos[7]=re.getString(8);
                  
                tabla.addRow(datos);
                
            }
        }
        catch (Exception e){
            System.out.print(e);
            
        }
    }

    public void Registrar(){
    try{
        fecha fec=new fecha();
    ps=cnn.prepareStatement("INSERT INTO tbcliente( CLItipdoc,CLIDoc,CLINom,CLIApll,CLIdir,CLItel,CLIUsu,CLIfech) values (?,?,?,?,?,?,?,?)");
    ps.setString(1,jTextTIPODO.getText());
    ps.setInt(2,Integer.parseInt(jTexDOcu.getText()));
    ps.setString(3,jTextNombre.getText());
    ps.setString(4,jTextApellido.getText());
    ps.setString(5,jTextDireccion.getText());
    ps.setString(6,jTextTelefono.getText());
    ps.setString(7,jTextusuario.getText());
    ps.setString(8,fec.cap(jDateChooserFecha));
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
    public void Eliminar(String dat){
        try{
        ps=cnn.prepareStatement("DELETE FROM tbcliente where  CLIDoc='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
     }
    
    public void Modificar(String tp,String nom ,String apll ,String dir ,String tel,String usu ,String fech,String doc  ){
        try{
            ps=cnn.prepareStatement("UPDATE tbcliente SET  CLItipdoc='"+ tp +"',CLINom='"+ nom+"',CLIApll='"+apll +"',CLIdir='"+ dir+"',CLItel='"+tel +"',CLIUsu='"+usu +"',CLIfech='"+fech +"' where CLIDoc='"+ doc+"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBuLIM = new javax.swing.JButton();
        jBuModifi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextTIPODO = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTexDOcu = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextusuario = new javax.swing.JTextField();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 790, 220));

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jBuLIM.setText("Limpiar");
        jBuLIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuLIMActionPerformed(evt);
            }
        });
        getContentPane().add(jBuLIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jBuModifi.setText("Modificar");
        jBuModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuModifiActionPerformed(evt);
            }
        });
        getContentPane().add(jBuModifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel1.setText("Apellido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel3.setText("Tipo documento ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("Documento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel8.setText("Fecha");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));
        getContentPane().add(jTextTIPODO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 30));
        getContentPane().add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 30));

        jTexDOcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexDOcuActionPerformed(evt);
            }
        });
        getContentPane().add(jTexDOcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 110, 30));
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 110, 30));
        getContentPane().add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 110, 30));

        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 110, 30));
        getContentPane().add(jTextusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 110, 30));
        getContentPane().add(jDateChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Menu m=new Menu();
       m.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Registrar ();
        Cargatabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String dat=jTexDOcu.getText();
        Eliminar(dat);
        Cargatabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBuLIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuLIMActionPerformed
       
        
    jTextTIPODO.setText(null);
    jTexDOcu.setText(null);
    jTextNombre.setText(null);
    jTextApellido.setText(null);
    jTextDireccion.setText(null);
    jTextTelefono.setText(null);
    jTextusuario.setText(null);
    jDateChooserFecha.setDate(null);

    }//GEN-LAST:event_jBuLIMActionPerformed

    private void jBuModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuModifiActionPerformed
       String tp,nom ,apll , dir ,tel,usu ,doc,fech;  
    
       tp=jTextTIPODO.getText();
       nom=jTextNombre.getText();
       apll=jTextApellido.getText();
       dir=jTextDireccion.getText();
       tel=jTextTelefono.getText();
       usu =jTextusuario.getText();
       fech=jDateChooserFecha.getDate();
       doc= jTexDOcu.getText();
        Modificar(tp, nom, apll, dir, tel, usu, fech, doc);
        Cargatabla();
    }//GEN-LAST:event_jBuModifiActionPerformed

    private void jTexDOcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexDOcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexDOcuActionPerformed

    private void jTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLIENTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuLIM;
    private javax.swing.JButton jBuModifi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexDOcu;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTIPODO;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextusuario;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables
}
